### ISSUE TITLE
Sample data required

### ISSUE THREAD

**Issue by jeremyklein** [HL7-DaVinci/CDex-CommReq-App#1]
Hi, would you be able to provide us with the sample fhir resources for Organization, Practitioner, Encounter, Claim, Patient used? This would be very helpful for getting the reference implementation running in the Logica sandbox.

**Comment by nschwertner** [comment]
The sample resources used in the MRP reference implementation are available at https://github.com/HL7-DaVinci/MRP-Sample-Patients

For the CDex use case, the sample resources were created by the CDex IG group directly in the reference implementation sandboxes (you can query them by way of Data Manager, FHIR API, etc):
https://sandbox.logicahealth.org/DaVinciCDexProvider
https://sandbox.logicahealth.org/DaVinciCDexPayer

In terms of testing the reference implementation, a CommunicationRequest for "History and Physical Notes" should match two documents in the provider sandbox.

**Comment by nschwertner** [comment]
Please submit all questions or support requests about the CDex RI here: https://chat.fhir.org/#narrow/stream/180805-Da-Vinci.20eCDx

**Comment by nschwertner** [comment]
For general DaVinci discussion/support: https://chat.fhir.org/#narrow/stream/179283-Da-Vinci
