### ISSUE TITLE
About Provider Organization and Practitioner details

### ISSUE THREAD

**Issue by suryarekha** [HL7-DaVinci/CDex-CommReq-App#2]
Hi All,
       In the CDex-CommReq-App we are considering the sender and requester data as static data. Is this the only way or can we consider them dynamically?? If we can consider them dynamically how is it possible?
Thanks in advance.

**Comment by nschwertner** [comment]
For DaVinci discussion/support: https://chat.fhir.org/#narrow/stream/179283-Da-Vinci
